"""
Iain Muir, iam9ez

"""
import os

# ------------ FOOTBALL ------------
FFL_LEAGUE_ID = 1080747
FFL_TEAM_ID = 4
FFL_POS_CODES = {
    0: 'QB', 1: 'TQB', 2: 'RB', 3: 'RB/WR', 4: 'WR', 5: 'WR/TE',
    6: 'TE', 7: 'OP',  8: 'DT', 9: 'DE', 10: 'LB', 11: 'DL',
    12: 'CB', 13: 'S', 14: 'DB', 15: 'DP', 16: 'D/ST', 17: 'K',
    18: 'P', 19: 'HC', 20: 'BE', 21: 'IR', 22: '', 23: 'RB/WR/TE',
    24: '', 25: 'Rookie'
}
FFL_DEFAULT_CODES = {
    1: 'QB', 2: 'RB', 3: 'WR', 4: 'TE', 5: 'K', 16: 'D/ST'
}
FFL_TEAM_MAP = {
    -16001: "atl",
    -16002: "buf",
    -16003: "chi",
    -16004: "cin",
    -16005: "cle",
    -16006: "dal",
    -16007: "den",
    -16008: "det",
    -16009: "gb",
    -16010: "ten",
    -16011: "ind",
    -16012: "kc",
    -16013: "lv",
    -16014: "lar",
    -16015: 'mia',
    -16016: "min",
    -16017: "ne",
    -16018: "no",
    -16019: "nyg",
    -16020: "nyj",
    -16021: "phi",
    -16022: "ari",
    -16023: "pit",
    -16024: "lac",
    -16025: "sf",
    -16026: "sea",
    -16027: "tb",
    -16028: "wsh",
    -16029: "car",
    -16030: "jax",
    -16033: 'bal',
    -16034: 'hou',
}

# ------------ BASKETBALL ------------
FBA_LEAGUE_ID = 1359582180
FBA_TEAM_ID = 5
FBA_POS_CODES = {
    0: 'PG',
    1: 'SG',
    2: 'SF',
    3: 'PF',
    4: 'C',
    5: 'G',
    6: 'F',
    7: 'SG/SF',
    8: 'G/F',
    9: 'PF/C',
    10: 'F/C',
    11: 'UT',
    12: 'BE',
    13: 'IR',
    14: '',
    15: 'Rookie',

    'PG': 0,
    'SG': 1,
    'SF': 2,
    'PF': 3,
    'C': 4,
    'G': 5,
    'F': 6,
    'SG/SF': 7,
    'G/F': 8,
    'PF/C': 9,
    'F/C': 10,
    'UT': 11,
    'BE': 12,
    'IR': 13,
    'Rookie': 15
}

FBA_TEAM_MAP = {
    0: 'FA',
    1: 'ATL',
    2: 'BOS',
    3: 'NOP',
    4: 'CHI',
    5: 'CLE',
    6: 'DAL',
    7: 'DEN',
    8: 'DET',
    9: 'GSW',
    10: 'HOU',
    11: 'IND',
    12: 'LAC',
    13: 'LAL',
    14: 'MIA',
    15: 'MIL',
    16: 'MIN',
    17: 'BKN',
    18: 'NYK',
    19: 'ORL',
    20: 'PHL',
    21: 'PHO',
    22: 'POR',
    23: 'SAC',
    24: 'SAS',
    25: 'OKC',
    26: 'UTA',
    27: 'WAS',
    28: 'TOR',
    29: 'MEM',
    30: 'CHA',
}

FBA_STATS_MAP = {
    '0': 'PTS',
    '1': 'BLK',
    '2': 'STL',
    '3': 'AST',
    '4': 'OREB',
    '5': 'DREB',
    '6': 'REB',
    '7': '',
    '8': '',
    '9': 'PF',
    '10': '',
    '11': 'TO',
    '12': '',
    '13': 'FGM',
    '14': 'FGA',
    '15': 'FTM',
    '16': 'FTA',
    '17': '3PTM',
    '18': '3PTA',
    '19': 'FG%',
    '20': 'FT%',
    '21': '3PT%',
    '22': '',
    '23': '',
    '24': '',
    '25': '',
    '26': '',
    '27': '',
    '28': 'MPG',
    '29': '',
    '30': '',
    '31': '',
    '32': '',
    '33': '',
    '34': '',
    '35': '',
    '36': '',
    '37': '',
    '38': '',
    '39': '',
    '40': 'MIN',
    '41': 'GP',
    '42': '',
    '43': '',
    '44': '',
    '45': '',
}

FBA_ACTIVITY_MAP = {
    178: 'FA ADDED',
    180: 'WAIVER ADDED',
    179: 'DROPPED',
    181: 'DROPPED',
    239: 'DROPPED',
    244: 'TRADED',
    'FA': 178,
    'WAIVER': 180,
    'TRADED': 244
}

import pandas as pd

LEAGUE_ID = 1080747

INDICES = {
    "NBA": 3,
    "MLB": 4,
    "NHL": 5,
    "Men's College Basketball": 7,
    "Premier League": 8,
    "MLS": 9,
    "La Liga": 10,
    "Bundesliga": 11,
    "Ligue 1": 12,
    "Serie A": 13,
    "Champions League": 14,
    "Europa League": 15,
    "NFL": 16
}

LOGOS = {
    "nba": "https://upload.wikimedia.org/wikipedia/en/0/03/National_Basketball_Association_logo.svg",
    "nfl": "https://upload.wikimedia.org/wikipedia/en/a/a2/National_Football_League_logo.svg",
    "mlb": "https://upload.wikimedia.org/wikipedia/en/a/a6/Major_League_Baseball_logo.svg",
    "nhl": "https://upload.wikimedia.org/wikipedia/en/3/3a/05_NHL_Shield.svg",
    "ncaab": "https://upload.wikimedia.org/wikipedia/commons/d/dd/NCAA_logo.svg",
    "epl": "https://upload.wikimedia.org/wikipedia/en/f/f2/Premier_League_Logo.svg",
    "mls": "https://upload.wikimedia.org/wikipedia/commons/7/76/MLS_crest_logo_RGB_gradient.svg",
    "liga": "https://upload.wikimedia.org/wikipedia/commons/1/13/LaLiga.svg",
    "bund": "https://upload.wikimedia.org/wikipedia/en/d/df/Bundesliga_logo_%282017%29.svg",
    "fran": "https://upload.wikimedia.org/wikipedia/en/b/ba/Ligue_1_Uber_Eats.svg",
    "seri": "https://upload.wikimedia.org/wikipedia/en/e/e1/Serie_A_logo_%282019%29.svg",
    "chlg": "https://upload.wikimedia.org/wikipedia/en/b/bf/UEFA_Champions_League_logo_2.svg",
    "uefa": "https://upload.wikimedia.org/wikipedia/en/0/03/Europa_League.svg"
}

CODES = {
    "NBA": "nba",
    "NFL": "nfl",
    "MLB": "mlb",
    "NHL": "nhl",
    "Men's College Basketball": "ncaab",
    "Premier League": "epl",
    "MLS": "mls",
    "La Liga": "liga",
    "Bundesliga": "bund",
    "Ligue 1": "fran",
    "Serie A": "seri",
    "Champions League": "chlg",
    "Europa League": "uefa"
}

LOGO_CODES = {
    "nba": "basketball",
    "nfl": "football",
    "mlb": "baseball",
    "nhl": "hockey",
    "ncaab": "basketball",
    "epl": "soccer",
    "mls": "soccer",
    "liga": "soccer",
    "bund": "soccer",
    "fran": "soccer",
    "seri": "soccer",
    "chlg": "soccer",
    "uefa": "soccer"
}

RESPONSE = pd.DataFrame(
    {'Timestamp': '7/21/2020 11:08:49',
     'Email Address': 'iam9ez@virginia.edu',
     'Sports League you would like to receive highlights from:': "NBA, NFL, MLB, NHL, Men's College Basketball,"
                                                                 " Premier League, MLS, La Liga, Bundesliga,"
                                                                 " Ligue 1, Serie A, Champions League, Europa League",
     'NBA Teams': 'BOS Celtics, BKN Nets, DAL Mavericks, DEN Nuggets, HOU Rockets, LA Clippers, LA Lakers,'
                  ' MEM Grizzlies, MIA Heat, MIL Bucks, NO Pelicans, PHI 76ers, TOR Raptors, WAS Wizards',
     'MLB Teams': 'BOS Red Sox, CHI Cubs, CLE Indians, COL Rockies, LA Angels, LA Dodgers, MIN Twins, NY Yankees,'
                  ' SF Giants, STL Cardinals, TB Rays, WSH Nationals',
     'NHL Teams': 'BOS Bruins, CHI Blackhawks, NY Rangers, PHI Flyers, PIT Penguins, SJ Sharks,'
                  ' TB Lightning, VGS Golden Knights, WAS Capitals',
     'Would you like condensed or full highlights?': 'Condensed',
     'NCAA Basketball Teams': 'Virginia, Duke, Notre Dame, Virginia Tech, North Carolina, Texas, Maryland,'
                              ' Ohio State, Michigan, Indiana, Arizona, Stanford, Kentucky, Florida, Georgia',
     'EPL Teams': 'Arsenal, Chelsea, Everton, Leicester City, Liverpool, Manchester City,'
                  ' Manchester United, Tottenham Hotspur',
     'MLS Teams': 'Atlanta, Chicago, D.C. United, LA Galaxy, LAFC, Minnesota,'
                  ' NYCFC, NY Red Bulls, Seattle',
     'La Liga Teams': 'Atlético Madrid, Barcelona, Real Madrid, Sevilla, Valencia',
     'Bundesliga Teams': 'Bayer Leverkusen, Bayern Munich, Dortmund, RB Leipzig, Werder Bremen',
     'Ligue 1 Teams': 'Lyon, Marseille, Montpellier, Nice, PSG, Saint-Etienne, Stade Rennes',
     'Serie A Teams': 'Fiorentina, Internazionale, Juventus, Lazio, Milan, Napoli, Roma',
     'Champions League Teams': 'Barcelona, Real Madrid, PSG, Juventus, Napoli, Roma, Bayern Munich,'
                               ' Dortmund, RB Leipzig, Liverpool, Manchester City, Manchester United',
     'Europa League Teams': 'Barcelona, Real Madrid, PSG, Juventus, Napoli, Roma, Bayern Munich, ' 
                            'Dortmund, RB Leipzig, Liverpool, Manchester City, Manchester United',
     'NFL Teams': 'ATL Falcons, BAL Ravens, CAR Panthers, CHI Bears, CLE Browns, DAL Cowboys, GB Packers, KC Chiefs,'
                  ' LA Rams, MIN Vikings, NE Patriots, NO Saints, SF 49ers, SEA Seahawks, WSH Football Team'
     }, index=[0]
)

if os.environ['USER'] == 'iainmuir':
    API_KEY = os.environ["API_KEY"]
else:
    API_KEY = 'bvgk9c748v6oab530k90'

NEWS_LOGOS = {
    'Home': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/CNBC_logo.svg',
    'Associated Press': 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Associated_Press_logo_2012.svg',
    'ESPN': 'https://upload.wikimedia.org/wikipedia/commons/2/2f/ESPN_wordmark.svg',
    'Financial Times': 'https://upload.wikimedia.org/wikipedia/commons/6/68/Financial_Times_masthead.svg',
    'Economist': 'https://upload.wikimedia.org/wikipedia/commons/6/65/The_Economist_Logo.svg'
}

DOW_JONES = [
    'BA',
    'DOW',
    'AXP',
    'CSCO',
    'JNJ',
    'GS',
    'IBM',
    'JPM',
    'WMT',
    'TRV',
    'HD',
    'NKE',
    'AAPL',
    'MMM',
    'MSFT',
    'PG',
    'CAT',
    'DIS',
    'UNH',
    'V',
    'CRM',
    'VZ',
    'WBA',
    'HON',
    'CVX',
    'MCD',
    'MRK',
    'KO',
    'INTC',
    'AMGN'
]

STATE_CODES = {
    'Washington, D.C.': 'DC', 'Mississippi': 'MS', 'Oklahoma': 'OK',
    'Delaware': 'DE', 'Minnesota': 'MN', 'Illinois': 'IL', 'Arkansas': 'AR',
    'New Mexico': 'NM', 'Indiana': 'IN', 'Maryland': 'MD', 'Louisiana': 'LA',
    'Idaho': 'ID', 'Wyoming': 'WY', 'Tennessee': 'TN', 'Arizona': 'AZ',
    'Iowa': 'IA', 'Michigan': 'MI', 'Kansas': 'KS', 'Utah': 'UT',
    'Virginia': 'VA', 'Oregon': 'OR', 'Connecticut': 'CT', 'Montana': 'MT',
    'California': 'CA', 'Massachusetts': 'MA', 'West Virginia': 'WV',
    'South Carolina': 'SC', 'New Hampshire': 'NH', 'Wisconsin': 'WI',
    'Vermont': 'VT', 'Georgia': 'GA', 'North Dakota': 'ND',
    'Pennsylvania': 'PA', 'Florida': 'FL', 'Alaska': 'AK', 'Kentucky': 'KY',
    'Hawaii': 'HI', 'Nebraska': 'NE', 'Missouri': 'MO', 'Ohio': 'OH',
    'Alabama': 'AL', 'Rhode Island': 'RI', 'South Dakota': 'SD',
    'Colorado': 'CO', 'New Jersey': 'NJ', 'Washington': 'WA',
    'North Carolina': 'NC', 'New York': 'NY', 'Texas': 'TX',
    'Nevada': 'NV', 'Maine': 'ME'
}

S_AND_P = [
    '--- Select a Company ---',
    '-- Other --',
    'Agilent Technologies Inc - A',
    'American Airlines Group - AAL',
    'Advance Auto Parts - AAP',
    'Apple Inc. - AAPL',
    'AbbVie Inc. - ABBV',
    'AmerisourceBergen Corp - ABC',
    'ABIOMED Inc - ABMD',
    'Abbott Laboratories - ABT',
    'Accenture plc - ACN',
    'Adobe Inc. - ADBE',
    'Analog Devices, Inc. - ADI',
    'Archer-Daniels-Midland Co - ADM',
    'Automatic Data Processing - ADP',
    'Autodesk Inc. - ADSK',
    'Ameren Corp - AEE',
    'American Electric Power - AEP',
    'AES Corp - AES',
    'AFLAC Inc - AFL',
    'American International Group - AIG',
    'Assurant - AIZ',
    'Arthur J. Gallagher & Co. - AJG',
    'Akamai Technologies Inc - AKAM',
    'Albemarle Corp - ALB',
    'Align Technology - ALGN',
    'Alaska Air Group Inc - ALK',
    'Allstate Corp - ALL',
    'Allegion - ALLE',
    'Alexion Pharmaceuticals - ALXN',
    'Applied Materials Inc. - AMAT',
    'Amcor plc - AMCR',
    'Advanced Micro Devices Inc - AMD',
    'AMETEK Inc. - AME',
    'Amgen Inc. - AMGN',
    'Ameriprise Financial - AMP',
    'American Tower Corp. - AMT',
    'Amazon.com Inc. - AMZN',
    'Arista Networks - ANET',
    'ANSYS - ANSS',
    'Anthem - ANTM',
    'Aon plc - AON',
    'A.O. Smith Corp - AOS',
    'Apache Corporation - APA',
    'Air Products & Chemicals Inc - APD',
    'Amphenol Corp - APH',
    'Aptiv PLC - APTV',
    'Alexandria Real Estate Equities - ARE',
    'Atmos Energy - ATO',
    'Activision Blizzard - ATVI',
    'AvalonBay Communities - AVB',
    'Broadcom Inc. - AVGO',
    'Avery Dennison Corp - AVY',
    'American Water Works Company Inc - AWK',
    'American Express Co - AXP',
    'AutoZone Inc - AZO',
    'Boeing Company - BA',
    'Bank of America Corp - BAC',
    'Baxter International Inc. - BAX',
    'Best Buy Co. Inc. - BBY',
    'Becton Dickinson - BDX',
    'Franklin Resources - BEN',
    'Brown-Forman Corp. - BF.B',
    'Biogen Inc. - BIIB',
    'Bio-Rad Laboratories - BIO',
    'The Bank of New York Mellon - BK',
    'Booking Holdings Inc - BKNG',
    'Baker Hughes Co - BKR',
    'BlackRock - BLK',
    'Ball Corp - BLL',
    'Bristol-Myers Squibb - BMY',
    'Broadridge Financial Solutions - BR',
    'Berkshire Hathaway - BRK.B',
    'Boston Scientific - BSX',
    'BorgWarner - BWA',
    'Boston Properties - BXP',
    'Citigroup Inc. - C',
    'Conagra Brands - CAG',
    'Cardinal Health Inc. - CAH',
    'Carrier Global - CARR',
    'Caterpillar Inc. - CAT',
    'Chubb Limited - CB',
    'Cboe Global Markets - CBOE',
    'CBRE Group - CBRE',
    'Crown Castle International Corp. - CCI',
    'Carnival Corp. - CCL',
    'Cadence Design Systems - CDNS',
    'CDW - CDW',
    'Celanese - CE',
    'Cerner - CERN',
    'CF Industries Holdings Inc - CF',
    'Citizens Financial Group - CFG',
    'Church & Dwight - CHD',
    'C. H. Robinson Worldwide - CHRW',
    'Charter Communications - CHTR',
    'CIGNA Corp. - CI',
    'Cincinnati Financial - CINF',
    'Colgate-Palmolive - CL',
    'The Clorox Company - CLX',
    'Comerica Inc. - CMA',
    'Comcast Corp. - CMCSA',
    'CME Group Inc. - CME',
    'Chipotle Mexican Grill - CMG',
    'Cummins Inc. - CMI',
    'CMS Energy - CMS',
    'Centene Corporation - CNC',
    'CenterPoint Energy - CNP',
    'Capital One Financial - COF',
    'Cabot Oil & Gas - COG',
    'The Cooper Companies - COO',
    'ConocoPhillips - COP',
    'Costco Wholesale Corp. - COST',
    'Campbell Soup - CPB',
    'Copart Inc - CPRT',
    'Salesforce.com - CRM',
    'Cisco Systems - CSCO',
    'CSX Corp. - CSX',
    'Cintas Corporation - CTAS',
    'Catalent - CTLT',
    'Cognizant Technology Solutions - CTSH',
    'Corteva - CTVA',
    'Citrix Systems - CTXS',
    'CVS Health - CVS',
    'Chevron Corp. - CVX',
    'Concho Resources - CXO',
    'Dominion Energy - D',
    'Delta Air Lines Inc. - DAL',
    'DuPont de Nemours Inc - DD',
    'Deere & Co. - DE',
    'Discover Financial Services - DFS',
    'Dollar General - DG',
    'Quest Diagnostics - DGX',
    'D. R. Horton - DHI',
    'Danaher Corp. - DHR',
    'The Walt Disney Company - DIS',
    'Discovery, Inc. (Class A) - DISCA',
    'Discovery, Inc. (Class C) - DISCK',
    'Dish Network - DISH',
    'Digital Realty Trust Inc - DLR',
    'Dollar Tree - DLTR',
    'Dover Corporation - DOV',
    'Dow Inc. - DOW',
    "Domino's Pizza - DPZ",
    'Duke Realty Corp - DRE',
    'Darden Restaurants - DRI',
    'DTE Energy Co. - DTE',
    'Duke Energy - DUK',
    'DaVita Inc. - DVA',
    'Devon Energy - DVN',
    'DXC Technology - DXC',
    'DexCom - DXCM',
    'Electronic Arts - EA',
    'eBay Inc. - EBAY',
    'Ecolab Inc. - ECL',
    'Consolidated Edison - ED',
    'Equifax Inc. - EFX',
    "Edison Int'l - EIX",
    'Estée Lauder Companies - EL',
    'Eastman Chemical - EMN',
    'Emerson Electric Company - EMR',
    'EOG Resources - EOG',
    'Equinix - EQIX',
    'Equity Residential - EQR',
    'Eversource Energy - ES',
    'Essex Property Trust, Inc. - ESS',
    'Eaton Corporation - ETN',
    'Entergy Corp. - ETR',
    'Etsy - ETSY',
    'Evergy - EVRG',
    'Edwards Lifesciences - EW',
    'Exelon Corp. - EXC',
    'Expeditors - EXPD',
    'Expedia Group - EXPE',
    'Extra Space Storage - EXR',
    'Ford Motor Company - F',
    'Diamondback Energy - FANG',
    'Fastenal Co - FAST',
    'Facebook, Inc. - FB',
    'Fortune Brands Home & Security - FBHS',
    'Freeport-McMoRan Inc. - FCX',
    'FedEx Corporation - FDX',
    'FirstEnergy Corp - FE',
    'F5 Networks - FFIV',
    'Fidelity National Information Services - FIS',
    'Fiserv Inc - FISV',
    'Fifth Third Bancorp - FITB',
    'FLIR Systems - FLIR',
    'Flowserve Corporation - FLS',
    'FleetCor Technologies Inc - FLT',
    'FMC Corporation - FMC',
    'Fox Corporation (Class B) - FOX',
    'Fox Corporation (Class A) - FOXA',
    'First Republic Bank - FRC',
    'Federal Realty Investment Trust - FRT',
    'TechnipFMC - FTI',
    'Fortinet - FTNT',
    'Fortive Corp - FTV',
    'General Dynamics - GD',
    'General Electric - GE',
    'Gilead Sciences - GILD',
    'General Mills - GIS',
    'Globe Life Inc. - GL',
    'Corning Inc. - GLW',
    'General Motors - GM',
    'Alphabet Inc. (Class C) - GOOG',
    'Alphabet Inc. (Class A) - GOOGL',
    'Genuine Parts - GPC',
    'Global Payments Inc. - GPN',
    'Gap Inc. - GPS',
    'Garmin Ltd. - GRMN',
    'Goldman Sachs Group - GS',
    'Grainger (W.W.) Inc. - GWW',
    'Halliburton Co. - HAL',
    'Hasbro Inc. - HAS',
    'Huntington Bancshares - HBAN',
    'Hanesbrands Inc - HBI',
    'HCA Healthcare - HCA',
    'Home Depot - HD',
    'Hess Corporation - HES',
    'HollyFrontier Corp - HFC',
    'Hartford Financial Svc.Gp. - HIG',
    'Huntington Ingalls Industries - HII',
    'Hilton Worldwide Holdings Inc - HLT',
    'Hologic - HOLX',
    "Honeywell Int'l Inc. - HON",
    'Hewlett Packard Enterprise - HPE',
    'HP Inc. - HPQ',
    'Hormel Foods Corp. - HRL',
    'Henry Schein - HSIC',
    'Host Hotels & Resorts - HST',
    'The Hershey Company - HSY',
    'Humana Inc. - HUM',
    'Howmet Aerospace - HWM',
    'International Business Machines - IBM',
    'Intercontinental Exchange - ICE',
    'IDEXX Laboratories - IDXX',
    'IDEX Corporation - IEX',
    'International Flavors & Fragrances - IFF',
    'Illumina Inc - ILMN',
    'Incyte - INCY',
    'IHS Markit Ltd. - INFO',
    'Intel Corp. - INTC',
    'Intuit Inc. - INTU',
    'International Paper - IP',
    'Interpublic Group - IPG',
    'IPG Photonics Corp. - IPGP',
    'IQVIA Holdings Inc. - IQV',
    'Ingersoll Rand - IR',
    'Iron Mountain Incorporated - IRM',
    'Intuitive Surgical Inc. - ISRG',
    'Gartner Inc - IT',
    'Illinois Tool Works - ITW',
    'Invesco Ltd. - IVZ',
    'Jacobs Engineering Group - J',
    'J. B. Hunt Transport Services - JBHT',
    'Johnson Controls International - JCI',
    'Jack Henry & Associates - JKHY',
    'Johnson & Johnson - JNJ',
    'Juniper Networks - JNPR',
    'JPMorgan Chase & Co. - JPM',
    'Kellogg Co. - K',
    'KeyCorp - KEY',
    'Keysight Technologies - KEYS',
    'Kraft Heinz Co - KHC',
    'Kimco Realty - KIM',
    'KLA Corporation - KLAC',
    'Kimberly-Clark - KMB',
    'Kinder Morgan - KMI',
    'Carmax Inc - KMX',
    'Coca-Cola Company - KO',
    'Kroger Co. - KR',
    'Kansas City Southern - KSU',
    'Loews Corp. - L',
    'L Brands Inc. - LB',
    'Leidos Holdings - LDOS',
    'Leggett & Platt - LEG',
    'Lennar Corp. - LEN',
    'Laboratory Corp. of America Holding - LH',
    'L3Harris Technologies - LHX',
    'Linde plc - LIN',
    'LKQ Corporation - LKQ',
    'Lilly (Eli) & Co. - LLY',
    'Lockheed Martin Corp. - LMT',
    'Lincoln National - LNC',
    'Alliant Energy Corp - LNT',
    "Lowe's Cos. - LOW",
    'Lam Research - LRCX',
    'Lumen Technologies - LUMN',
    'Southwest Airlines - LUV',
    'Las Vegas Sands - LVS',
    'Lamb Weston Holdings Inc - LW',
    'LyondellBasell - LYB',
    'Live Nation Entertainment - LYV',
    'Mastercard Inc. - MA',
    'Mid-America Apartments - MAA',
    "Marriott Int'l. - MAR",
    'Masco Corp. - MAS',
    "McDonald's Corp. - MCD",
    'Microchip Technology - MCHP',
    'McKesson Corp. - MCK',
    "Moody's Corp - MCO",
    'Mondelez International - MDLZ',
    'Medtronic plc - MDT',
    'MetLife Inc. - MET',
    'MGM Resorts International - MGM',
    'Mohawk Industries - MHK',
    'McCormick & Co. - MKC',
    'MarketAxess - MKTX',
    'Martin Marietta Materials - MLM',
    'Marsh & McLennan - MMC',
    '3M Company - MMM',
    'Monster Beverage - MNST',
    'Altria Group Inc - MO',
    'The Mosaic Company - MOS',
    'Marathon Petroleum - MPC',
    'Merck & Co. - MRK',
    'Marathon Oil Corp. - MRO',
    'Morgan Stanley - MS',
    'MSCI Inc - MSCI',
    'Microsoft Corp. - MSFT',
    'Motorola Solutions Inc. - MSI',
    'M&T Bank Corp. - MTB',
    'Mettler Toledo - MTD',
    'Micron Technology - MU',
    'Maxim Integrated Products Inc - MXIM',
    'Norwegian Cruise Line Holdings - NCLH',
    'Nasdaq, Inc. - NDAQ',
    'NextEra Energy - NEE',
    'Newmont Corporation - NEM',
    'Netflix Inc. - NFLX',
    'NiSource Inc. - NI',
    'Nike, Inc. - NKE',
    'NortonLifeLock - NLOK',
    'Nielsen Holdings - NLSN',
    'Northrop Grumman - NOC',
    'National Oilwell Varco Inc. - NOV',
    'ServiceNow - NOW',
    'NRG Energy - NRG',
    'Norfolk Southern Corp. - NSC',
    'NetApp - NTAP',
    'Northern Trust Corp. - NTRS',
    'Nucor Corp. - NUE',
    'Nvidia Corporation - NVDA',
    'NVR, Inc. - NVR',
    'Newell Brands - NWL',
    'News Corp. Class B - NWS',
    'News Corp. Class A - NWSA',
    'Realty Income Corporation - O',
    'Old Dominion Freight Line - ODFL',
    'ONEOK - OKE',
    'Omnicom Group - OMC',
    'Oracle Corp. - ORCL',
    "O'Reilly Automotive - ORLY",
    'Otis Worldwide - OTIS',
    'Occidental Petroleum - OXY',
    'Paycom - PAYC',
    'Paychex Inc. - PAYX',
    "People's United Financial - PBCT",
    'PACCAR Inc. - PCAR',
    'Healthpeak Properties - PEAK',
    'Public Service Enterprise Group (PSEG) - PEG',
    'PepsiCo Inc. - PEP',
    'Pfizer Inc. - PFE',
    'Principal Financial Group - PFG',
    'Procter & Gamble - PG',
    'Progressive Corp. - PGR',
    'Parker-Hannifin - PH',
    'PulteGroup - PHM',
    'Packaging Corporation of America - PKG',
    'PerkinElmer - PKI',
    'Prologis - PLD',
    'Philip Morris International - PM',
    'PNC Financial Services - PNC',
    'Pentair plc - PNR',
    'Pinnacle West Capital - PNW',
    'Pool Corporation - POOL',
    'PPG Industries - PPG',
    'PPL Corp. - PPL',
    'Perrigo - PRGO',
    'Prudential Financial - PRU',
    'Public Storage - PSA',
    'Phillips 66 - PSX',
    'PVH Corp. - PVH',
    'Quanta Services Inc. - PWR',
    'Pioneer Natural Resources - PXD',
    'PayPal - PYPL',
    'QUALCOMM Inc. - QCOM',
    'Qorvo - QRVO',
    'Royal Caribbean Group - RCL',
    'Everest Re Group Ltd. - RE',
    'Regency Centers Corporation - REG',
    'Regeneron Pharmaceuticals - REGN',
    'Regions Financial Corp. - RF',
    'Robert Half International - RHI',
    'Raymond James Financial Inc. - RJF',
    'Ralph Lauren Corporation - RL',
    'ResMed - RMD',
    'Rockwell Automation Inc. - ROK',
    'Rollins Inc. - ROL',
    'Roper Technologies - ROP',
    'Ross Stores - ROST',
    'Republic Services Inc - RSG',
    'Raytheon Technologies - RTX',
    'SBA Communications - SBAC',
    'Starbucks Corp. - SBUX',
    'Charles Schwab Corporation - SCHW',
    'Sealed Air - SEE',
    'Sherwin-Williams - SHW',
    'SVB Financial - SIVB',
    'JM Smucker - SJM',
    'Schlumberger Ltd. - SLB',
    'SL Green Realty - SLG',
    'Snap-on - SNA',
    'Synopsys Inc. - SNPS',
    'Southern Company - SO',
    'Simon Property Group Inc - SPG',
    'S&P Global, Inc. - SPGI',
    'Sempra Energy - SRE',
    'STERIS plc - STE',
    'State Street Corp. - STT',
    'Seagate Technology - STX',
    'Constellation Brands - STZ',
    'Stanley Black & Decker - SWK',
    'Skyworks Solutions - SWKS',
    'Synchrony Financial - SYF',
    'Stryker Corp. - SYK',
    'Sysco Corp. - SYY',
    'AT&T Inc. - T',
    'Molson Coors Beverage Company - TAP',
    'TransDigm Group - TDG',
    'Teledyne Technologies - TDY',
    'TE Connectivity Ltd. - TEL',
    'Teradyne - TER',
    'Truist Financial - TFC',
    'Teleflex - TFX',
    'Target Corp. - TGT',
    'Tiffany & Co. - TIF',
    'TJX Companies Inc. - TJX',
    'Thermo Fisher Scientific - TMO',
    'T-Mobile US - TMUS',
    'Tapestry, Inc. - TPR',
    'T. Rowe Price Group - TROW',
    'The Travelers Companies Inc. - TRV',
    'Tractor Supply Company - TSCO',
    'Tesla, Inc. - TSLA',
    'Tyson Foods - TSN',
    'Trane Technologies plc - TT',
    'Take-Two Interactive - TTWO',
    'Twitter, Inc. - TWTR',
    'Texas Instruments - TXN',
    'Textron Inc. - TXT',
    'Tyler Technologies - TYL',
    'Under Armour (Class C) - UA',
    'Under Armour (Class A) - UAA',
    'United Airlines Holdings - UAL',
    'UDR, Inc. - UDR',
    'Universal Health Services - UHS',
    'Ulta Beauty - ULTA',
    'UnitedHealth Group Inc. - UNH',
    'Unum Group - UNM',
    'Union Pacific Corp - UNP',
    'United Parcel Service - UPS',
    'United Rentals, Inc. - URI',
    'U.S. Bancorp - USB',
    'Visa Inc. - V',
    'Varian Medical Systems - VAR',
    'VF Corporation - VFC',
    'ViacomCBS - VIAC',
    'Valero Energy - VLO',
    'Vulcan Materials - VMC',
    'Vornado Realty Trust - VNO',
    'Vontier - VNT',
    'Verisk Analytics - VRSK',
    'Verisign Inc. - VRSN',
    'Vertex Pharmaceuticals Inc - VRTX',
    'Ventas Inc - VTR',
    'Viatris - VTRS',
    'Verizon Communications - VZ',
    'Westinghouse Air Brake Technologies Corp - WAB',
    'Waters Corporation - WAT',
    'Walgreens Boots Alliance - WBA',
    'Western Digital - WDC',
    'WEC Energy Group - WEC',
    'Welltower Inc. - WELL',
    'Wells Fargo - WFC',
    'Whirlpool Corp. - WHR',
    'Willis Towers Watson - WLTW',
    'Waste Management Inc. - WM',
    'Williams Companies - WMB',
    'Walmart - WMT',
    'W. R. Berkley Corporation - WRB',
    'WestRock - WRK',
    'West Pharmaceutical Services - WST',
    'Western Union Co - WU',
    'Weyerhaeuser - WY',
    'Wynn Resorts Ltd - WYNN',
    'Xcel Energy Inc - XEL',
    'Xilinx - XLNX',
    'Exxon Mobil Corp. - XOM',
    'Dentsply Sirona - XRAY',
    'Xerox - XRX',
    'Xylem Inc. - XYL',
    'Yum! Brands Inc - YUM',
    'Zimmer Biomet - ZBH',
    'Zebra Technologies - ZBRA',
    'Zions Bancorp - ZION',
    'Zoetis - ZTS',
]
